name: Deploy to Alwaysdata

on:
  push:
    branches:
      - main # o el nombre de tu rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.7' # o la versión de PHP que estás utilizando

      - name: Install Dependencies
        run: composer install # si estás utilizando Composer para gestionar dependencias

      - name: Deploy to Alwaysdata
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: '/public_html/'
          local-dir: './'